### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Stetocasa** [andrea-mattioli/bticino_x8000_component#36]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed/try to install the latest version

### The problem

Hello, following you guide, the point 2.1, not clear what configure and where. 
seems configuration about current accessory or integration. I’m stuck
Thanks for your precious job here

### On which thermostat you have the issue?

X8000

### Which version of the Bticino X8000 component are you using?

??

### Which version of Home Assistant are you using?

??

### What type of installation are you running?

Home Assistant OS

**Comment by engal89** [comment]
Hi, yes the passage is missing in the documentation because is based on the previous version of the integration and is not updated. Before passage 2.1 (we can say 2.0) you have to log in in Home Assistant, go to Settings, Devices and services > Add integration > Find "Bticino X8000" > and put there the settings. Obviusly only after you have installed the integration from HACS.

**Comment by Stetocasa** [comment]
thanks, now is clear, but in hacs not appear the Bticino x8000 (only the official Bticino released by Netatmo)

I was thinking to install the "componenti aggiuntivi" but when I install the repository this error appear 
<img width="674" alt="Screenshot 2024-09-25 alle 09 59 57" src="https://github.com/user-attachments/assets/be0e3e1b-46d7-4239-9c32-96f0439e576a">

maybe I need to install the repository v2?

**Comment by engal89** [comment]
See #11

**Comment by Stetocasa** [comment]
ALL DONE !!!!

SEI UN MITO

**Comment by engal89** [comment]
If resolved, close the issue.
