### ISSUE TITLE
Data not updating with Cloudflare tunnel

### ISSUE THREAD

**Issue by DjMayone** [andrea-mattioli/bticino_x8000_component#9]
### Question

Hi Andrea, I have correctly configured the new component and I can correctly see the two thermostats installed. The only thing is that the data is not updated: for example the temperature detected by the component is not the same as that shown on the APP. Could it be that I'm exposing Homeassistant via a Cloudflare tunnel?

**Comment by andrea-mattioli** [comment]
Yes, I also have problems with cloudflare and the DNS proxy, I had to remove it and expose the public IP.
I have a pfsense firewall with HA proxy with ACLs and I have thus secured my infrastructure.Even Alexa doesn't work for me with the proxy active, I haven't figured out why yet but the HA app doesn't work for me either!
Indeed, if you know how to solve the problem with Alexa and the HA app, maybe we can find the root cause of the problem also for sending data from Legrand!

**Comment by DjMayone** [comment]
> Yes, I also have problems with cloudflare and the DNS proxy, I had to remove it and expose the public IP. I have a pfsense firewall with HA proxy with ACLs and I have thus secured my infrastructure.Even Alexa doesn't work for me with the proxy active, I haven't figured out why yet but the HA app doesn't work for me either! Indeed, if you know how to solve the problem with Alexa and the HA app, maybe we can find the root cause of the problem also for sending data from Legrand!

I wish I could help you but I have no way to expose Homeassistant other than with the Cloudflare tunnel because I'm behind a 5G connection with double NAT and I have no other way to publish externally. I have Alexa but not configured in Homeassistant, for now I let it work on its own. The strange thing is that the Companion APP works correctly, wouldn't it be necessary to also put the ports (MQTT?) used by the thermostats in the tunnel?

**Comment by andrea-mattioli** [comment]
It doesn't use mqtt, the data arrives via http post on a ha webhook

**Comment by DjMayone** [comment]
> It doesn't use mqtt, the data arrives via http post on a ha webhook

Let me know if I could do anything...

**Comment by DjMayone** [comment]
Hi Andrea, I did a test: within the integration, by selecting system options, I disabled and enabled polling for updates. The two thermostats took the correct values ​​at that time. This means that they can communicate correctly with the Legrand cloud via Cloudflare tunnel. I don't understand why it doesn't do it automatically...

**Comment by andrea-mattioli** [comment]
If you don't wait for the data to arrive from Legrand but you make the query it's different, it's one thing to do get on their servers and another to receive posts on your HA's webhooks

**Comment by andrea-mattioli** [comment]
Try:

1. Go to Cloudflare’s dashboard on their website, Zero Trust > Access > Tunnels. Select your tunnel. (This is where the Tunnel ID comes from for the Cloudflare Tunnel Token above.)

2. Check that everything is correct. The public hostname and service target (http://yourip:8123) must be right. Verify that remote access to that domain still works.

3. Go to Cloudflare’s dashboard, Zero Trust > Access > Access Groups. Create a new group, named whatever you like. I used “Google Assistant IPs”.

4. Under Group Configuration > Include, selector IP ranges, add the following ranges.

| Geography          | Region                        | IP V4 ranges        |
|--------------------|-------------------------------|---------------------|
| Australia          | Australia East                | 20.37.194.0/24      |
|                           |Australia South East | 20.42.226.0/24               |
| Brazil             | Brazil South                  | 191.235.226.0/24    |
| Canada             | Central Canada                | 52.228.82.0/24      |
| Asia Pacific       | Southeast Asia (Singapore)    | 20.195.68.0/24      |
| India              | South India                   | 20.41.194.0/24      |
|                    | Central India                 | 20.204.197.192/26   |
| United States      | Central United States         | 20.37.158.0/23      |
|                    | West Central United States    | 52.150.138.0/24     |
|                    | East United States            | 20.42.5.0/24        |
|                    | East 2 United States          | 20.41.6.0/23        |
|                    | North United States           | 40.80.187.0/24      |
|                    | South United States           | 40.119.10.0/24      |
|                    | West United States            | 40.82.252.0/24      |
|                    | West 2 United States          | 20.42.134.0/23      |
|                    | West 3 United States          | 20.125.155.0/24     |
| Europe             | Western Europe                | 40.74.28.0/23       |
|                    | North Europe                  | 20.166.41.0/24      |
| United Kingdom     | United Kingdom South          | 51.104.26.0/24      |

It would be a good idea to also ask Legrand support a question to find out which regions they have the services distributed in, otherwise I'm afraid you'll have to open all those subnets.
[Here](https://learn.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops&tabs=IP-V4) you will find the link to the AZURE page, I hope it can help you.

**Comment by DjMayone** [comment]
Ciao Andrea, I traced with my firewall the domain my smarther(s) contact from inside my lan to Legrand cloud. Could be helpful in your opinion?

**Comment by DjMayone** [comment]
@andrea-mattioli what I have to ask exactly to Legrand forum?

**Comment by andrea-mattioli** [comment]
have you tried following [those steps](https://github.com/andrea-mattioli/bticino_x8000_component/issues/9#issuecomment-1941746143)?

**Comment by DjMayone** [comment]
> have you tried following [those steps](https://github.com/andrea-mattioli/bticino_x8000_component/issues/9#issuecomment-1941746143)?

Not yet... is it safe in your opinion add all the subnets?

**Comment by andrea-mattioli** [comment]
Make a test by adding all the subnets, if it works then write to Legrand and ask which ones you need to implement and remove the rest!

Also you can try make a POST (use internet connection):
```
import requests
import json

def send_post_request(url, payload):
    headers = {'Content-Type': 'application/json'}
    try:
        response = requests.post(url, data=json.dumps(payload), headers=headers)
        if response.status_code == 200:
            print("POST request successful!")
            print("Response:")
            print(response.json())
        else:
            print("POST request failed with status code:", response.status_code)
            print("Response:")
            print(response.text)
    except Exception as e:
        print("An error occurred:", e)

# payload JSON
payload = {
    "key1": "value1",
    "key2": "value2"
}

#  URL
url = "https://example.com/api/webhook/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

#  POST
send_post_request(url, payload)
```

You can find the correct endpoint url via Legrand API or via my old integration http://HAIP:5588/c2c_subscription

**Comment by DjMayone** [comment]
Ciao Andrea, I've added all the subnets to cloudflare tunnel and now seems to work. Meanwhile I've made a post in Legrand forum asking for the correct subnet. You'll find it in forum.

**Comment by andrea-mattioli** [comment]
Great!!!

**Comment by DjMayone** [comment]
> Great!!!

Make a check on Legrand forum, just to be updated ;)

**Comment by ivanlouis87** [comment]
Hi Andrea,
I'm replying here because I think my issue is related (sorry if I'm missing some configuration steps). My 4 thermostats' reported data are not updating too, but I'm not on a cloud flare tunnel. I have indeed a reverse proxy with swag (nginix), Could it be something related to swag then? do I have to configure some extra port? 
Thanks in advance! 
Ivano
<img width="1119" alt="Screenshot 2024-02-21 alle 16 40 20" src="https://github.com/andrea-mattioli/bticino_x8000_component/assets/45461391/c57aa100-eb1b-4b60-b2d1-0b51bd4c4cac">

**Comment by andrea-mattioli** [comment]
no, the port uses the default external address of the home assistant.
if you don't receive data check the reverse proxy logs.
above in the comments there is a script to send posts to the thermostats address, try it and see the return code.
If you have blocks on the reverse proxy, remove them and see if it works for you.
Legrand sends POST to a webhook address, and must be reachable from outside on the HA address.

**Comment by DjMayone** [comment]
Ciao Andrea, mi sorge un dubbio: nella guida indichi di inserire come "first reply url" https://my.home-assistant.io nell'app di Legrand. Essendo con Cloudflare devo lasciare quella od indicare il link che espongo? (https://ha-casamia.miodominio.me)
Stessa cosa per il link che viene generato all'interno del custom component.
Grazie ancora!
